language: python

sudo: false

python:
  - "2.7"
  - "3.5"

env:
  - TOXENV=py27
  - TOXENV=py35

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install tox

script: tox
